# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JavaScript-XRay
version:      1.01
version_from: lib/JavaScript/XRay.pm
installdirs:  site
requires:
    Carp:                          0
    File::Basename:                0
    File::Spec::Functions:         0
    Getopt::Long:                  0
    LWP::Simple:                   0
    Pod::Usage:                    0
    Test::More:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
